# Generated by Django 5.1.5 on 2025-01-29 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('momo', '0002_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.AddField(
            model_name='post',
            name='tag',
            field=models.ManyToManyField(help_text='Add tags to post', to='momo.tag'),
        ),
    ]
