# Generated by Django 5.1.5 on 2025-02-01 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('momo', '0005_remove_post_tag_delete_tag'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tags',
        ),
    ]
